INSERT INTO item_colors(item_colors.color_name) values
("red"),
    ("pink"),
    ("purple"),
    ("deepPurple"),
    ("indigo"),
    ("blue"),
    ("lightBlue"),
    ("cyan"),
    ("teal"),
    ("green"),
    ("lightGreen"),
   ( "lime"),
    ("yellow"),
    ("amber"),
    ("orange"),
    ("deepOrange"),
    ("brown"),
("blueGrey"),
 ("redAccent"),
    ("pinkAccent"),
    ("purpleAccent"),
    ("deepPurpleAccent"),
    ("indigoAccent"),
    ("blueAccent"),
    ("lightBlueAccent"),
    ("cyanAccent"),
    ("tealAccent"),
    ("greenAccent"),
    ("lightGreenAccent"),
    ("limeAccent"),
    ("yellowAccent"),
    ("amberAccent"),
    ("orangeAccent"),
    ("deepOrangeAccent");

