INSERT INTO `variation_option` (`id`, `value`, `variation_id`) VALUES
 (NULL, 'red', '1'),
 (NULL, 'blue', '1'),
 (NULL, 'pink', '1'),
 (NULL, 'purple', '1'),
 (NULL, 'deepPurple', '1'),
 (NULL, 'indigo', '1'),
 (NULL, 'lightBlue', '1'),
 (NULL, 'cyan', '1'),
 (NULL, 'teal', '1'),
 (NULL, 'green', '1'),
 (NULL, 'lightGreen', '1'),
 (NULL, 'lime', '1'),
 (NULL, 'yellow', '1'),
 (NULL, 'amber', '1'),
 (NULL, 'orange', '1'),
 (NULL, 'deepOrange', '1'),
 (NULL, 'brown', '1'),
 (NULL, 'blueGrey', '1'),
 (NULL, 'redAccent', '1'),
 (NULL, 'pinkAccent', '1'),
 (NULL, 'purpleAccent', '1'),
 (NULL, 'deepPurpleAccent', '1'),
 (NULL, 'indigoAccent', '1'),
 (NULL, 'blueAccent', '1'),
 (NULL, 'lightBlueAccent', '1'),
 (NULL, 'cyanAccent', '1'),
 (NULL, 'tealAccent', '1'),
 (NULL, 'greenAccent', '1'),
 (NULL, 'lightGreenAccent', '1'),
 (NULL, 'limeAccent', '1'),
 (NULL, 'yellowAccent', '1'),
 (NULL, 'amberAccent', '1'),
 (NULL, 'orangeAccent', '1'),
 (NULL, 'deepOrangeAccent', '1');


redAccent,
    pinkAccent,
    purpleAccent,
    deepPurpleAccent,
    indigoAccent,
    blueAccent,
    lightBlueAccent,
    cyanAccent,
    tealAccent,
    greenAccent,
    lightGreenAccent,
    limeAccent,
    yellowAccent,
    amberAccent,
    orangeAccent,
    deepOrangeAccent,